### ISSUE TITLE
Setup KanBan board

### ISSUE THREAD

**Issue by EidHachem** [EidHachem/RecipeOnRails#8]
In this project, we are a team of two members @mavericks-db  and @EidHachem 

here is the link for the project [RecipeOnRails](https://github.com/EidHachem/RecipeOnRails/projects/1)

Happy coding 🎉🎉🎉

**Comment by emmanuellekamwa** [comment]
**STATUS: APPROVED 🍾✔🎉**
Hello @EidHachem and @mavericks-db 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Your linters are passing all the checks
- You asked for the changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mavericksbalitaan** [comment]
Thank you 👍
